/* The following code was generated by JFlex 1.3.5 on 1/18/22, 2:14 AM */

// import section
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 1/18/22, 2:14 AM from the specification file
 * <tt>file:/Users/demba/Downloads/ipetrovic6319rn/MPLexer.flex</tt>
 */
class MPLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;
  final public static int COMMENT = 1;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  5,  0,  0,  6,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     6,  0,  0,  0,  0,  0,  7,  0, 17, 18, 10,  9, 16, 11, 37,  4, 
    35,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0, 15, 12, 13, 14,  0, 
     0,  3,  3,  3,  3, 38,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  1, 
     0, 23, 34, 28, 31, 30, 33, 22, 29, 25,  1,  1,  1, 24, 26, 21, 
    19,  1, 20,  1, 27,  1,  1, 32, 36,  1,  1,  0,  8,  0,  0,  0
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    39,    78,   117,   156,   195,    78,   234,   273,    78, 
       78,    78,   312,   351,   390,    78,    78,    78,    78,   429, 
      468,   507,   546,   585,   624,   663,   702,   741,   780,   819, 
      858,   897,    78,   780,   936,   975,   780,   780,   780,  1014, 
     1053,  1092,   780,   780,   780,   780,  1131,  1170,  1209,  1248, 
     1287,  1326,  1365,  1404,  1443,  1482,    78,    78,    78,    78, 
       78,    78,    78,  1521,  1560,  1599,  1638,  1677,  1716,  1755, 
     1794,  1833,   780,  1872,   780,   780,   780,   780,   780,   780, 
      780,  1911,  1950,  1989,  2028,  2067,  2106,  2145,  2184,  2223, 
     2262,  2301,  2340,   117,  2379,   117,  2418,   117,  2457,  1833, 
     2496,  2535,  2574,   819,  2613,   819,  2652,   819,  2691,  2223, 
     2730,  2769,   117,   117,  2808,  2847,  2886,  2925,   819,   819, 
     2964,  3003,  3042,  3042,  3081,   117,   117,  3120,  3120,  3159, 
      819,   819,  3198,  3237,   117,   819
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\1\5\1\4\1\6\2\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\4\4\1\26\2\4\1\27"+
    "\1\4\1\30\1\4\1\31\1\32\1\33\1\34\1\4"+
    "\1\3\1\4\1\35\1\36\1\37\1\36\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\1\60\4\36"+
    "\1\61\2\36\1\62\1\36\1\63\1\36\1\64\1\65"+
    "\1\66\1\67\1\36\1\35\1\36\50\0\3\4\17\0"+
    "\22\4\1\0\1\4\2\0\1\5\40\0\1\5\1\0"+
    "\1\70\5\0\1\71\51\0\1\72\47\0\1\73\53\0"+
    "\1\74\1\75\45\0\1\76\46\0\1\77\32\0\3\4"+
    "\17\0\1\4\1\100\20\4\1\0\1\4\1\0\3\4"+
    "\17\0\13\4\1\101\6\4\1\0\1\4\1\0\3\4"+
    "\17\0\7\4\1\102\12\4\1\0\1\4\1\0\3\4"+
    "\17\0\12\4\1\103\7\4\1\0\1\4\1\0\3\4"+
    "\17\0\7\4\1\104\12\4\1\0\1\4\1\0\3\4"+
    "\17\0\1\4\1\105\20\4\1\0\1\4\1\0\3\4"+
    "\17\0\2\4\1\106\17\4\1\0\1\4\1\0\3\4"+
    "\17\0\13\4\1\107\6\4\1\0\1\4\2\0\1\5"+
    "\40\0\1\5\1\110\1\70\1\0\5\111\1\41\42\111"+
    "\3\36\1\111\1\41\15\111\22\36\1\111\1\36\2\111"+
    "\1\37\2\111\1\41\35\111\1\37\1\111\1\112\5\111"+
    "\1\113\1\41\46\111\1\41\1\111\1\114\44\111\1\41"+
    "\2\111\1\115\43\111\1\41\7\111\1\116\1\117\35\111"+
    "\1\41\7\111\1\120\36\111\1\41\7\111\1\121\32\111"+
    "\3\36\1\111\1\41\15\111\1\36\1\122\20\36\1\111"+
    "\1\36\1\111\3\36\1\111\1\41\15\111\13\36\1\123"+
    "\6\36\1\111\1\36\1\111\3\36\1\111\1\41\15\111"+
    "\7\36\1\124\12\36\1\111\1\36\1\111\3\36\1\111"+
    "\1\41\15\111\12\36\1\125\7\36\1\111\1\36\1\111"+
    "\3\36\1\111\1\41\15\111\7\36\1\126\12\36\1\111"+
    "\1\36\1\111\3\36\1\111\1\41\15\111\1\36\1\127"+
    "\20\36\1\111\1\36\1\111\3\36\1\111\1\41\15\111"+
    "\2\36\1\130\17\36\1\111\1\36\1\111\3\36\1\111"+
    "\1\41\15\111\13\36\1\131\6\36\1\111\1\36\2\111"+
    "\1\37\2\111\1\41\35\111\1\37\1\132\1\112\1\111"+
    "\2\0\1\133\40\0\1\133\4\0\3\4\17\0\2\4"+
    "\1\134\17\4\1\0\1\4\1\0\3\4\17\0\4\4"+
    "\1\135\15\4\1\0\1\4\1\0\3\4\17\0\10\4"+
    "\1\136\11\4\1\0\1\4\1\0\3\4\17\0\4\4"+
    "\1\137\15\4\1\0\1\4\1\0\3\4\17\0\14\4"+
    "\1\140\5\4\1\0\1\4\1\0\3\4\17\0\6\4"+
    "\1\141\13\4\1\0\1\4\1\0\3\4\17\0\1\4"+
    "\1\142\20\4\1\0\1\4\1\0\3\4\17\0\3\4"+
    "\1\143\16\4\1\0\1\4\2\0\2\144\37\0\1\144"+
    "\2\0\1\144\2\111\1\145\2\111\1\41\35\111\1\145"+
    "\4\111\3\36\1\111\1\41\15\111\2\36\1\146\17\36"+
    "\1\111\1\36\1\111\3\36\1\111\1\41\15\111\4\36"+
    "\1\147\15\36\1\111\1\36\1\111\3\36\1\111\1\41"+
    "\15\111\10\36\1\150\11\36\1\111\1\36\1\111\3\36"+
    "\1\111\1\41\15\111\4\36\1\151\15\36\1\111\1\36"+
    "\1\111\3\36\1\111\1\41\15\111\14\36\1\152\5\36"+
    "\1\111\1\36\1\111\3\36\1\111\1\41\15\111\6\36"+
    "\1\153\13\36\1\111\1\36\1\111\3\36\1\111\1\41"+
    "\15\111\1\36\1\154\20\36\1\111\1\36\1\111\3\36"+
    "\1\111\1\41\15\111\3\36\1\155\16\36\1\111\1\36"+
    "\2\111\2\156\1\111\1\41\35\111\1\156\2\111\1\156"+
    "\2\0\1\133\40\0\1\133\2\0\1\157\1\0\3\4"+
    "\17\0\3\4\1\160\16\4\1\0\1\4\1\0\3\4"+
    "\17\0\14\4\1\161\5\4\1\0\1\4\1\0\3\4"+
    "\17\0\1\4\1\162\20\4\1\0\1\4\1\0\3\4"+
    "\17\0\10\4\1\163\11\4\1\0\1\4\1\0\3\4"+
    "\17\0\6\4\1\164\13\4\1\0\1\4\2\111\1\145"+
    "\2\111\1\41\35\111\1\145\2\111\1\165\1\111\3\36"+
    "\1\111\1\41\15\111\3\36\1\166\16\36\1\111\1\36"+
    "\1\111\3\36\1\111\1\41\15\111\14\36\1\167\5\36"+
    "\1\111\1\36\1\111\3\36\1\111\1\41\15\111\1\36"+
    "\1\170\20\36\1\111\1\36\1\111\3\36\1\111\1\41"+
    "\15\111\10\36\1\171\11\36\1\111\1\36\1\111\3\36"+
    "\1\111\1\41\15\111\6\36\1\172\13\36\1\111\1\36"+
    "\2\0\1\173\6\0\1\174\1\0\1\174\27\0\1\173"+
    "\4\0\3\4\17\0\1\4\1\175\20\4\1\0\1\4"+
    "\1\0\3\4\17\0\13\4\1\176\6\4\1\0\1\4"+
    "\1\0\3\4\17\0\7\4\1\177\12\4\1\0\1\4"+
    "\2\111\1\200\2\111\1\41\3\111\1\201\1\111\1\201"+
    "\27\111\1\200\4\111\3\36\1\111\1\41\15\111\1\36"+
    "\1\202\20\36\1\111\1\36\1\111\3\36\1\111\1\41"+
    "\15\111\13\36\1\203\6\36\1\111\1\36\1\111\3\36"+
    "\1\111\1\41\15\111\7\36\1\204\12\36\1\111\1\36"+
    "\2\0\1\173\40\0\1\173\4\0\3\4\17\0\4\4"+
    "\1\205\15\4\1\0\1\4\2\111\1\200\2\111\1\41"+
    "\35\111\1\200\4\111\3\36\1\111\1\41\15\111\4\36"+
    "\1\206\15\36\1\111\1\36\1\0\3\4\17\0\5\4"+
    "\1\207\14\4\1\0\1\4\1\111\3\36\1\111\1\41"+
    "\15\111\5\36\1\210\14\36\1\111\1\36";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  1,  1,  9,  1,  1,  9,  9,  9,  1,  1,  1,  9, 
     9,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  0,  9,  9,  9,  9,  9,  9,  9,  1, 
     1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1, 
     1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1, 
     0,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
 public int getLine()
   {
      return yyline;
   }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  MPLexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  MPLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3276];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 134: 
        case 135: 
          {  return new Symbol( sym.PROGRAM );	 }
        case 137: break;
        case 62: 
        case 80: 
          {  return new Symbol( sym.GREATE );  }
        case 138: break;
        case 13: 
        case 40: 
          {  return new Symbol( sym.ASSIGN );  }
        case 139: break;
        case 6: 
        case 33: 
          {  ;  }
        case 140: break;
        case 97: 
        case 107: 
          {  return new Symbol( sym.FOR );	 }
        case 141: break;
        case 95: 
        case 105: 
          {  return new Symbol( sym.END );	 }
        case 142: break;
        case 93: 
        case 103: 
          {  return new Symbol( sym.INT );	 }
        case 143: break;
        case 61: 
        case 79: 
          {  return new Symbol( sym.EQ );  }
        case 144: break;
        case 60: 
        case 78: 
          {  return new Symbol( sym.NEQ );  }
        case 145: break;
        case 58: 
        case 76: 
          {  return new Symbol( sym.OR );  }
        case 146: break;
        case 57: 
        case 75: 
          {  return new Symbol( sym.AND);  }
        case 147: break;
        case 11: 
        case 38: 
          {  return new Symbol( sym.MIN );  }
        case 148: break;
        case 10: 
        case 37: 
          {  return new Symbol( sym.MUL );  }
        case 149: break;
        case 9: 
        case 36: 
          {  return new Symbol( sym.PLUS);  }
        case 150: break;
        case 5: 
        case 31: 
          {  return new Symbol( sym.DIV );  }
        case 151: break;
        case 17: 
        case 44: 
          {  return new Symbol( sym.LP );  }
        case 152: break;
        case 18: 
        case 45: 
          {  return new Symbol( sym.RP );  }
        case 153: break;
        case 32: 
          {  yybegin( YYINITIAL );  }
        case 154: break;
        case 2: 
        case 7: 
        case 8: 
        case 28: 
        case 34: 
        case 35: 
          {  if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: " + yytext() );  }
        case 155: break;
        case 15: 
        case 42: 
          {  return new Symbol( sym.DOTCOMMA );  }
        case 156: break;
        case 99: 
        case 109: 
          {  return new Symbol( sym.CONST, yytext(), yyline, yycolumn );  }
        case 157: break;
        case 4: 
        case 27: 
        case 30: 
        case 54: 
          {  return new Symbol( sym.CONST, yytext(), yyline, yycolumn );  }
        case 158: break;
        case 122: 
        case 127: 
          {  return new Symbol( sym.REAL,yytext(), yyline, yycolumn ); }
        case 159: break;
        case 3: 
        case 19: 
        case 20: 
        case 21: 
        case 22: 
        case 23: 
        case 24: 
        case 25: 
        case 26: 
        case 29: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 63: 
        case 64: 
        case 65: 
        case 66: 
        case 67: 
        case 68: 
        case 69: 
        case 70: 
        case 81: 
        case 82: 
        case 83: 
        case 84: 
        case 85: 
        case 86: 
        case 87: 
        case 88: 
        case 91: 
        case 92: 
        case 94: 
        case 96: 
        case 98: 
        case 101: 
        case 102: 
        case 104: 
        case 106: 
        case 108: 
        case 111: 
        case 114: 
        case 115: 
        case 117: 
        case 120: 
        case 121: 
        case 124: 
        case 129: 
        case 132: 
        case 133: 
          {  return new Symbol(sym.ID, yyline, yytext());  }
        case 160: break;
        case 56: 
        case 74: 
          {  yybegin( COMMENT );  }
        case 161: break;
        case 126: 
        case 131: 
          {  return new Symbol( sym.BEGIN );	 }
        case 162: break;
        case 125: 
        case 130: 
          {  return new Symbol( sym.WRITE );	 }
        case 163: break;
        case 113: 
        case 119: 
          {  return new Symbol( sym.CHAR );	 }
        case 164: break;
        case 112: 
        case 118: 
          {  return new Symbol( sym.READ );	 }
        case 165: break;
        case 59: 
        case 77: 
          {  return new Symbol( sym.LESSE );  }
        case 166: break;
        case 12: 
        case 39: 
          {  return new Symbol( sym.LESS );  }
        case 167: break;
        case 14: 
        case 41: 
          {  return new Symbol( sym.GREAT );  }
        case 168: break;
        case 16: 
        case 43: 
          {  return new Symbol( sym.COMMA );  }
        case 169: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new Symbol( sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
