
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 18 02:12:13 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATE = 17;
  public static final int READ = 5;
  public static final int AND = 12;
  public static final int DOTCOMMA = 21;
  public static final int PLUS = 8;
  public static final int INT = 27;
  public static final int OR = 13;
  public static final int LP = 22;
  public static final int CHAR = 28;
  public static final int RP = 23;
  public static final int END = 4;
  public static final int ID = 25;
  public static final int WRITE = 6;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 3;
  public static final int COMMA = 20;
  public static final int GREAT = 16;
  public static final int EOF = 0;
  public static final int DIV = 11;
  public static final int error = 1;
  public static final int ASSIGN = 24;
  public static final int EQ = 18;
  public static final int MIN = 9;
  public static final int BOOL = 29;
  public static final int LESSE = 15;
  public static final int FOR = 7;
  public static final int REAL = 26;
  public static final int NEQ = 19;
  public static final int MUL = 10;
  public static final int LESS = 14;
}

